---
- name: Restart opencontrail-analytics-nodemgr container
  vars:
    service_name: "opencontrail-analytics-nodemgr"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_analytics_nodemgr_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_analytics_nodemgr_container | changed
- name: Restart opencontrail-analytics-api container
  vars:
    service_name: "opencontrail-analytics-api"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_analytics_api_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_analytics_api_container | changed
- name: Restart opencontrail-analytics-collector container
  vars:
    service_name: "opencontrail-analytics-collector"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_analytics_collector_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_analytics_collector_container | changed
- name: Restart opencontrail-analytics-query-engine container
  vars:
    service_name: "opencontrail-analytics-query-engine"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_analytics_query_engine_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_analytics_query_engine_container | changed
- name: Restart opencontrail-analytics-alarm-gen container
  vars:
    service_name: "opencontrail-analytics-alarm-gen"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_analytics_alarm_gen_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_analytics_alarm_gen_container | changed
- name: Restart opencontrail-analytics-topology container
  vars:
    service_name: "opencontrail-analytics-topology"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_analytics_topology_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_analytics_topology_container | changed
- name: Restart opencontrail-analytics-snmp-collector container
  vars:
    service_name: "opencontrail-analytics-snmp-collector"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_analytics_snmp_collector_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_analytics_snmp_collector_container | changed
