---
- name: Restart opencontrail-config-nodemgr container
  vars:
    service_name: "opencontrail-config-nodemgr"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_config_nodemgr_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_config_nodemgr_container | changed
- name: Restart opencontrail-config-api container
  vars:
    service_name: "opencontrail-config-api"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_config_api_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_config_api_container | changed
- name: Restart opencontrail-config-devicemgr container
  vars:
    service_name: "opencontrail-config-devicemgr"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_config_devicemgr_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_config_devicemgr_container | changed
- name: Restart opencontrail-config-schema container
  vars:
    service_name: "opencontrail-config-schema"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_config_schema_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_config_schema_container | changed
- name: Restart opencontrail-config-svcmonitor container
  vars:
    service_name: "opencontrail-config-svcmonitor"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_config_svcmonitor_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_config_svcmonitor_container | changed
