---
- name: Restart opencontrail-configdb-nodemgr container
  vars:
    service_name: "opencontrail-configdb-nodemgr"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_configdb_nodemgr_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_configdb_nodemgr_container | changed
- name: Restart opencontrail-configdb-zookeeper container
  vars:
    service_name: "opencontrail-configdb-zookeeper"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_configdb_zookeeper_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_configdb_zookeeper_container | changed
- name: Restart opencontrail-configdb-cassandra container
  vars:
    service_name: "opencontrail-configdb-cassandra"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_configdb_cassandra_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_configdb_cassandra_container | changed
