---
- name: Restart opencontrail-vrouter-agent-nodemgr container
  vars:
    service_name: "opencontrail-vrouter-agent-nodemgr"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_vrouter_agent_nodemgr_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_vrouter_agent_nodemgr_container | changed
- name: Restart opencontrail-vrouter-agent container
  vars:
    service_name: "opencontrail-vrouter-agent"
    service: "{{ opencontrail_services[service_name] }}"
    opencontrail_vrouter_agent_container: "{{ check_opencontrail_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged }}"
    volumes: "{{ service.volumes }}"
    environment: "{{ service.environment }}"
  when:
    - action != "config"
    - service.enabled | bool
    - service.host_in_groups | bool
    - opencontrail_vrouter_agent_container | changed
