---
- name: Pulling Opencontrail images
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ item.value.image }}"
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ opencontrail_services | combine(opencontrail_init_services) }}"
